name: CI Pipeline

on:
  push:
    branches:
      - master  # Ajustado para o branch principal do seu repositório
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Ajuste para a versão usada no projeto
    
    - name: Install torch
      run: |
        pip install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: install opencv-python
      run: |
        pip install opencv-python

    - name: Install Detectron2
      run: |
        pip install detectron2==0.6 -f   https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html

    - name: Run tests
      run: |
        pytest -q tests/  # Comando para executar os testes, conforme o README